version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
      - export REVISION=$(git rev-parse --short HEAD)
  build:
    commands:
      - npm run build
      - sed -i "s/{{REVISION}}/$REVISION/" ./config/prod.json
      - sed -i "s/{{REVISION}}/$REVISION/" ./config/staging.json
artifacts:
  files:
    - 'buildspec/**/*'
    - 'dist/**/*'
    - 'config/**/*'
