version: 0.2

env:
  variables:
    PROJECT_PATH: ./dist/angular-build-once-deploy-anywhere
phases:
  build:
    commands:
      - cp ./config/${ENV}.json ${PROJECT_PATH}/assets/config.json
      - aws s3 cp --recursive ${PROJECT_PATH}/ s3://${BUCKET}/${ENV}/
      - aws s3 sync --delete ${PROJECT_PATH}/ s3://${BUCKET}/${ENV}/
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/${ENV}/*"
artifacts:
  files:
    - 'dist/**/*'
